In [2]:
import numpy as np
import os

def save_npz_to_csv(npz_path, output_dir):
    # Load the .npz file
    npz_file = np.load(npz_path)
    
    # Ensure the output directory exists
    os.makedirs(output_dir, exist_ok=True)
    
    for array_name in npz_file.files:
        array_data = npz_file[array_name]
        print(array_name)
        print(array_data)
        if array_data.ndim == 1 or array_data.ndim == 2:
            None
            # Handle 1D or 2D arrays directly
            #output_filename = os.path.join(output_dir, f'{array_name}.csv')
            #np.savetxt(output_filename, array_data, delimiter=',')
            #print(f'Saved array "{array_name}" to {output_filename}')
        
        elif array_data.ndim == 3:
            # Handle 3D arrays by saving each 2D slice
            depth = array_data.shape[0]
            print(depth)
            for i in range(depth):
                slice_data = array_data[i]
                #slice_filename = os.path.join(output_dir, f'{array_name}_slice_{i}.csv')
                #np.savetxt(slice_filename, slice_data, delimiter=',')
                #print(f'Saved slice {i} of array "{array_name}" to {slice_filename}')
        
        else:
            print(f'Array "{array_name}" has {array_data.ndim} dimensions, which is not supported.')

# Usage
npz_file_path = 'your_file.npz'  # Replace with your .npz file path
output_directory = 'csv_output'  # Replace with your desired output directory
save_npz_to_csv('data\DASHlink_binary_Flaps_noAnomaly_test.npz', 'data/')


data
[[[0.4094141  0.20052478 0.39400703 ... 0.50603014 0.24178617 0.39183578]
  [0.3917268  0.19925475 0.39044902 ... 0.5170181  0.2417519  0.39277422]
  [0.4085754  0.1985015  0.37242934 ... 0.51184034 0.24047978 0.35959107]
  ...
  [0.73382515 0.059395   0.13749906 ... 0.5149137  0.24534181 0.03559416]
  [0.7565789  0.05945489 0.1337864  ... 0.50955707 0.24580196 0.033277  ]
  [0.7481928  0.05905931 0.1327206  ... 0.501955   0.24548087 0.06391364]]

 [[0.26818734 0.23385237 0.40081993 ... 0.4878716  0.45544258 0.43897042]
  [0.27151972 0.23242939 0.39636117 ... 0.49332944 0.454319   0.44206074]
  [0.27497643 0.23103757 0.38907525 ... 0.49474874 0.4542292  0.44148257]
  ...
  [0.4397751  0.07318635 0.16631664 ... 0.5254856  0.41091496 0.25423333]
  [0.4609738  0.07223    0.16362798 ... 0.5187142  0.41143292 0.25998694]
  [0.5174611  0.07134065 0.15180323 ... 0.51151866 0.41136822 0.24016804]]

 [[0.5635266  0.20329563 0.20369545 ... 0.5084159  0.4233134  0.43062913]
  [0.51369363 0.2